In [ ]:
import pandas as pd
import numpy as np

## THE BASICS

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimension
a.ndim

1

In [5]:
# Get Shape
b.shape

(2, 3)

In [6]:
# Get Type
a.dtype

dtype('int32')

In [7]:
# Get Size
a.itemsize

4

In [8]:
# Get total size
a.nbytes

12

In [9]:
# Get number of elements
a.size

3

## ### Accessing/Changing specific elements, rows, columns, etc

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Get a specific element [r, c]
a[1, 5]

13

In [12]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [14]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [15]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### 3-D example

In [16]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
# Get specific element (work outside in)
b[0,1,1]

4

In [18]:
b.shape

(2, 2, 2)

In [20]:
# replace 
#b[:,1,:] = [[9,9,9],[8,8]]

In [21]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### ### Initializing Different Types of Arrays

In [22]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [29]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [30]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [31]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.46633013, 0.90137713],
       [0.63767258, 0.73874758],
       [0.11394628, 0.16542448],
       [0.38570035, 0.69436957]])

In [32]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 1,  0, -1],
       [-1, -1,  2],
       [-3, -1,  5]])

In [35]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [41]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## ##### Be careful when copying arrays!!!

In [48]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


### MATHEMATICS

In [49]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [50]:
a + 2

array([3, 4, 5, 6])

In [51]:
a -2

array([-1,  0,  1,  2])

In [52]:
a * 2

array([2, 4, 6, 8])

In [53]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [54]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [55]:
a ** 2

array([ 1,  4,  9, 16])

In [56]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

## LINEAR ALGEBRA

In [57]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [59]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

## ## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

## STATISTICS

In [60]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
np.min(stats)

1

In [64]:
np.max(stats, axis=1)

array([3, 6])

In [65]:
np.sum(stats, axis=0)

array([5, 7, 9])

## ### Reorganizing Arrays

In [66]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [67]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [68]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [71]:
filedata = np.genfromtxt(r"D:\FREECODECAMP\20\NumPy-master\data.txt", delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


## ##### Boolean Masking and Advanced Indexing

In [72]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [73]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])